In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Working with Dates
* Converting to datetime datatype

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### 1. Extract year

In [9]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
916 2019-07-13        2457        3      25       2019
182 2019-05-26        1135       28       1       2019
832 2019-01-11        4445       25       1       2019
627 2018-08-01        4568       13     138       2018
43  2018-09-04        2490        7       1       2018

#### 2. Extract Month

In [10]:
date['date_month'] = date['date'].dt.month

date.sample(5)

          date  product_id  city_id  orders  date_year  date_month
115 2018-10-13        5779       13       6       2018          10
375 2019-07-14        2002        1       3       2019           7
910 2019-04-25        2504        2       2       2019           4
463 2018-11-21        1945        9       3       2018          11
259 2019-12-10        7246       13       1       2019          12

#### 3. Extract Month Name

In [11]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### 4. Extract Days

In [12]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

#### 5. Day of Week

In [13]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

#### 6. Day of Week - Name

In [14]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

#### 7. is weekend?

In [15]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

#### 8. Extract week of the year

In [17]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

#### 9. Extract Quarter

In [18]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

#### 10. Extract Semester

In [19]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

#### 11. Extract Time elapsed between dates

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 10, 22, 10, 48, 58, 45065)

In [21]:
today - date['date']

0     2508 days 10:48:58.045065
1     2990 days 10:48:58.045065
2     2921 days 10:48:58.045065
3     2623 days 10:48:58.045065
4     2846 days 10:48:58.045065
                 ...
995   2936 days 10:48:58.045065
996   2877 days 10:48:58.045065
997   2725 days 10:48:58.045065
998   2790 days 10:48:58.045065
999   2564 days 10:48:58.045065
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
(today - date['date']).dt.days

0      2508
1      2990
2      2921
3      2623
4      2846
       ...
995    2936
996    2877
997    2725
998    2790
999    2564
Name: date, Length: 1000, dtype: int64

#### 12. Months passed

In [27]:
today = pd.Timestamp.today().normalize()
date['date'] = pd.to_datetime(date['date'])

date['months_passed'] = (
    (today - date['date']) / np.timedelta64(1, 'D') / 30.44
).round(0)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester,months_ago,months_passed
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2,82,82.0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2,98,98.0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2,96,96.0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2,86,86.0
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1,93,93.0

## Working with Times

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

#### 1. Converting to datetime datatype

In [29]:
time['date'] = pd.to_datetime(time['date'])

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

#### 2. Extract Hour, Min, and Sec

In [31]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

#### 3. Extract Time part

In [32]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

#### 4. Time difference

In [33]:
today - time['date']

0     4693 days 23:10:00
1     4558 days 00:20:00
2     5043 days 23:39:00
3     4345 days 23:29:00
4     4743 days 00:49:00
             ...
995   5332 days 23:10:00
996   4654 days 00:46:00
997   5119 days 00:23:00
998   5235 days 00:26:00
999   4507 days 00:35:00
Name: date, Length: 1000, dtype: timedelta64[ns]

#### 5. in seconds

In [34]:
(today - time['date'])/np.timedelta64(1,'s')

0      405558600.0
1      393812400.0
2      435800340.0
3      375492540.0
4      409798140.0
          ...
995    460768200.0
996    402108360.0
997    442282980.0
998    452305560.0
999    389406900.0
Name: date, Length: 1000, dtype: float64

#### 6. in minutes

In [35]:
(today - time['date'])/np.timedelta64(1,'m')

0      6759310.0
1      6563540.0
2      7263339.0
3      6258209.0
4      6829969.0
         ...
995    7679470.0
996    6701806.0
997    7371383.0
998    7538426.0
999    6490115.0
Name: date, Length: 1000, dtype: float64

#### 7. in hours

In [36]:
(today - time['date'])/np.timedelta64(1,'h')

0      112655.166667
1      109392.333333
2      121055.650000
3      104303.483333
4      113832.816667
           ...
995    127991.166667
996    111696.766667
997    122856.383333
998    125640.433333
999    108168.583333
Name: date, Length: 1000, dtype: float64